install.packages("tm")
install.packages("SnowballC")
install.packages("wordcloud")
install.packages("RColorBrewer")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("shinythemes")
install.packages("readr")

library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library(shiny)
library(shinydashboard)
library(shinythemes)
library(readr)